# GitLab CI jobs for processing controller

.env: &env
  variables:
    BUILD_PATH: src/processing_controller

# ============================================================================
# Test Python package
# ============================================================================

test:processing_controller:
  extends:
    - .test_python
    - .test_with_coverage
  <<: *env

# ============================================================================
# Build Docker development image
# ============================================================================

build:processing_controller:
  extends: .build_docker
  <<: *env

publish:processing_controller:
  extends: .push_docker_nexus
  dependencies:
    - build:processing_controller
  <<: *env
