# Local Gitlab-CI file for Processing Controller

## ============================================================================
## Build, tag and push Docker development images
## ============================================================================

# This needs to be updated. Might be best to use Gitlab registry for
# development images, otherwise it will load the nexus registry with lots of
# development images.

# Build and push `processing_controller` image.
build:processing_controller:
  stage: build
  extends: .build_docker
  variables:
    BUILD_PATH: src/processing_controller

## ============================================================================
## Test Docker development images
## ============================================================================

# Placeholder for testing. Currently not doing anything.
test:processing_controller:
  stage: test
  extends: .pull_docker
  variables:
    BUILD_PATH: src/processing_controller
  script:
    - echo "Placeholder for testing docker images"

## ============================================================================
## Tag and push Docker latest images (master only)
## ============================================================================

.processing_controller_template:
  stage: publish
  extends: .push_docker
  when: always
  dependencies:
    - build:processing_controller
  variables:
    BUILD_PATH: src/processing_controller

publish:processing_controller:
  extends: .processing_controller_template
  only: [master]