# GitLab CI jobs for processing controller

# ============================================================================
# Test Python package
# ============================================================================

test:processing_controller:
  extends: .test_python
  script:
    - cd src/processing_controller
    - python3 setup.py test
    # Make the coverage report available at the top level, which will merge it.
    - mv .coverage ../../$CI_JOB_NAME.coverage
  artifacts:
    paths:
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

# ============================================================================
# Build Docker development image
# ============================================================================

build:processing_controller:
  extends: .build_docker
  variables:
    BUILD_PATH: src/processing_controller

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:processing_controller:
  extends: .push_docker_nexus
  dependencies:
    - build:processing_controller
  variables:
    BUILD_PATH: src/processing_controller
